### ISSUE TITLE
Nginx configuration per site type

### ISSUE THREAD

**Issue by maxi032** [phalcon/box#67]
Is there a way to set an `nginx.conf` per site like Homestead allows it? 

For instance in Homestead you can specify something like:
```yml
- map: slayer.home
  to: /home/vagrant/Code/slayer/public      
  type: slayer
```
and this creates a `serve-slayer.sh`
