### ISSUE TITLE
Nginx config uses PHP socket, PHP config uses ip.add.re.ss:port.

### ISSUE THREAD

**Issue by NathMorgan** [phalcon/box#74]
## Steps to reproduce

> Provide minimal script/step to reproduce the issue

1. Vagrant up
2. Load page

### Expected behavior

> Renders page

### Actual behavior

> 502 Bad Gateway

### Host operating system

> MacOS Sierra

### `settings.yml`

```yaml
---
# ------------------------------------------------------------
# Phalcon Box Configurations
# ------------------------------------------------------------
#

# Name of VM
name: pbox

# Enable GUI mode (show screen of VM)
gui: false

ip: "192.168.50.4"

# memory (in MB):
#   auto -> 1/4 of system RAM
#   1536 -> 1.5 GB RAM
memory: 2048

# cpu:
#   auto -> max number of CPU cores
#      2 -> 2 CPU cores
cpus: 2

# vram (in MB):
#   video memory (currently vbox only)
vram: 100

folders:
    - map: ~/Documents/development/phalcon-projects/scritch.me
      to: /home/vagrant/workspace/scritch.es

# Sites configuration.
#
# You can use the "type" parameter to specify the type
# of Nginx configuration for the site. For example:
#
# - map:  landing.local
#   to:   /home/vagrant/workspace/landing/public
#   type: spa
#
# The default type is "phalcon".
#
# If the desired type is not allowed "phalcon" will be used as fallback.
#
# Available types:
#   - phalcon
#   - slayer
#   - phanbook
#   - proxy
#   - spa
#   - silverstripe
#   - symfony2
#   - statamic
#   - laravel
sites:
    - map: scritch.es.dev
      to:  /home/vagrant/workspace/scritch.es/public

databases:
    - scritches

#blackfire:
#    - id: foo
#      token: bar
#      client-id: foo
#      client-token: bar

#ports:
#    - send: 50000
#      to: 5000
#    - send: 7777
#      to: 777
#      protocol: udp
```

### Vagrant up output

https://gist.github.com/NathMorgan/37fa03643665625098b42628d66d1167

### Details

- Vagrant: Vagrant 1.9.1
- Provider: Virtualbox 5.1.14
- Phalcon Box: v2.2.2
- Operating System: MacOS Sierra

Changing /etc/php/7.1/fpm/pool.d/www.conf listen = ip.add.re.ss:port to listen = /var/run/php/php7.1-fpm.sock fixed this issue.
