### ISSUE TITLE
Mod-Rewrite is not enabled

### ISSUE THREAD

**Issue by pablomoreno61** [phalcon/box#79]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

## Steps to reproduce

> Provide minimal script/step to reproduce the issue

1. just open my local url
2. see this message:
Mod-Rewrite is not enabled

Please enable rewrite module on your web server to continue

### Expected behavior

Show phalcon skeleton default page

> Describe what you are trying to achieve and what goes wrong.

Mod-Rewrite is not enabled

Please enable rewrite module on your web server to continue

> What actually happened?

from macOs to ubuntu from phalconbox

> This is the operating system that you run locally.

### `settings.yml`

```yaml
---
# ------------------------------------------------------------
# Phalcon Box Configurations
# ------------------------------------------------------------
#

# Name of VM
name: pbox

# VM provider
#
# Available providers:
#   - virtualbox
#   - vmware_fusion
#   - vmware_workstation
provider: virtualbox

# Enable GUI mode (show screen of VM)
gui: false

ip: "192.168.50.4"

# memory (in MB):
#   auto -> 1/4 of system RAM
#   1536 -> 1.5 GB RAM
memory: 2048

# cpu:
#   auto -> max number of CPU cores
#      2 -> 2 CPU cores
cpus: 2

# vram (in MB):
#   video memory (currently vbox only)
vram: 100

# Provisioning features
provision:
  # do full system update for each full provisoning
  update: true

  # apt packages
  apt: []

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/workspace
      to: /Users/pablomoreno/vagrant/workspace

# Sites configuration.
#
# You can use the "type" parameter to specify the type
# of Nginx configuration for the site. For example:
#
# - map:  landing.local
#   to:   /home/vagrant/workspace/landing/public
#   type: spa
#
# The default type is "phalcon".
#
# If the desired type is not allowed "phalcon" will be used as fallback.
#
# Available types:
#   - phalcon
#   - slayer
#   - phanbook
#   - proxy
#   - spa
#   - silverstripe
#   - symfony2
#   - statamic
#   - laravel
#   - zend
sites:
    - map: tfg.consupermiso.com
      to:  /Users/pablomoreno/vagrant/workspace/tfg
      type: phalcon
      domains:
        - 192.168.50.4  tfg.consupermiso.com

databases:
    - phalcondb

#blackfire:
#    - id: foo
#      token: bar
#      client_id: foo
#      client_token: bar

#ports:
#    - send: 50000
#      to: 5000
#    - send: 7777
#      to: 777
#      protocol: udp

# verbose:
#   Set provision verbosity to obtain detailed logging.
#   Default value is false (minimal verbosity). Examples:
#
#   false -> minimal verbosity
#    true -> equivalent to v
#    -vvv -> equivalent to vvv
#    vvvv -> maximal verbosity
verbose: false
```

### Vagrant up output

> Provide output if related.
> Provide a link to a GitHub Gist containing the complete output.
> Do NOT paste the debug output in the issue, just paste the link to the Gist.

### Details

- Vagrant: Run `vagrant -v` to show the version
- Provider: Virtualbox, VMWare or Parallels and it's version
- Phalcon Box: Run `git describe --tags --abbrev=0` to show the version
- Operating System:
- Other related info (if any):

NOTE: A lot of issues can be resolved by simply updating Vagrant, VM provider or Phalcon Box.

Virtualbox users, please upgrade to `~5.1`. You will show as up-to-date from the `~5.0` branch when you
`About -> Check for Updates`. You'll need to download a newer version of Virtualbox. 
See: https://www.virtualbox.org/wiki/Downloads

### References

Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...
