### ISSUE TITLE
File not found message after up the box

### ISSUE THREAD

**Issue by isaactzab** [phalcon/box#81]
## Steps to reproduce

I have installed the box, added host name to host file, then I tried to acces to http://phalcon.local/ and "File not found." message has been displayed.
Also I have added a file with phpinfo function and mapped the folders.

### Expected behavior

> Display "index.php" file

### Actual behavior

> "File not found." message has been displayed.

### Host operating system

> Linux Ubuntu Xenial 16.04 LTS

### `settings.yml`

```yaml
---
# ------------------------------------------------------------
# Phalcon Box Configurations
# ------------------------------------------------------------
#

# Name of VM
name: pbox

# VM provider
#
# Available providers:
#   - virtualbox
#   - vmware_fusion
#   - vmware_workstation
provider: virtualbox

# Enable GUI mode (show screen of VM)
gui: false

ip: "192.168.50.4"

# memory (in MB):
#   auto -> 1/4 of system RAM
#   1536 -> 1.5 GB RAM
memory: 2048

# cpu:
#   auto -> max number of CPU cores
#      2 -> 2 CPU cores
cpus: 2

# vram (in MB):
#   video memory (currently vbox only)
vram: 100

# Provisioning features
provision:
    # do full system update for each full provisoning
    update: true

    # apt packages
    apt: []

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/www/public
      to: /home/vagrant/workspace/phalcon

# Sites configuration.
#
# You can use the "type" parameter to specify the type
# of Nginx configuration for the site. For example:
#
# - map:  landing.local
#   to:   /home/vagrant/workspace/landing/public
#   type: spa
#
# The default type is "phalcon".
#
# If the desired type is not allowed "phalcon" will be used as fallback.
#
# Available types:
#   - phalcon
#   - slayer
#   - phanbook
#   - proxy
#   - spa
#   - silverstripe
#   - symfony2
#   - statamic
#   - laravel
#   - zend
sites:
    - map: phalcon.local
      to:  /home/vagrant/workspace/phalcon/public

databases:
    - phalcondb

#blackfire:
#    - id: foo
#      token: bar
#      client_id: foo
#      client_token: bar

#ports:
#    - send: 50000
#      to: 5000
#    - send: 7777
#      to: 777
#      protocol: udp

# verbose:
#   Set provision verbosity to obtain detailed logging.
#   Default value is false (minimal verbosity). Examples:
#
#   false -> minimal verbosity
#    true -> equivalent to v
#    -vvv -> equivalent to vvv
#    vvvv -> maximal verbosity
verbose: false

```

### Details

- Vagrant: 1.9.5
- Provider: Virtualbox 5.0.22 r108108
- Phalcon Box: v2.5.0
- Operating System: Linux Ubuntu Xenial 16.04 LTS

**Comment by sergeyklay** [comment]
```yaml
folders:
    - map: ~/www/public
      to: /home/vagrant/workspace/phalcon

sites:
    - map: phalcon.local
      to:  /home/vagrant/workspace/phalcon/public
```

Note, folders' `map` is path to the project files, NOT public filer. For example:

1. Host system
    * Project path: `/home/user/www/myproject`
    * Public root: `/home/user/www/myproject/public`
    * Index file: `/home/user/www/myproject/public/index.php`

2. Config
```yaml
folders:
    - map: ~/www/myproject # OR /home/user/www/myproject
      to: /home/vagrant/workspace/myproject

sites:
    - map: phalcon.local
      to:  /home/vagrant/workspace/myproject/public
```

Also you don't need to edit hosts file by hand. Just install [**`vagrant-hostsupdater`**](https://github.com/cogitatio/vagrant-hostsupdater).
