### ISSUE TITLE
Getting `gsub!': can't modify frozen String (RuntimeError) on vagrant up

### ISSUE THREAD

**Issue by Zaszczyk** [phalcon/box#82]
## Steps to reproduce
1. ./install
2. vagrant up

### Expected behavior

Vagrant should run normally.

### Actual behavior

Vagrant shutdown VM, log: https://gist.github.com/Zaszczyk/c640538155080df116e70c275e613c66

### Host operating system
macOS 10.12.5

### `settings.yml`

```yaml
---
# ------------------------------------------------------------
# Phalcon Box Configurations
# ------------------------------------------------------------
#

# Name of VM
name: pbox

# VM provider
#
# Available providers:
#   - virtualbox
#   - vmware_fusion
#   - vmware_workstation
provider: virtualbox

# Enable GUI mode (show screen of VM)
gui: false

ip: "192.168.50.4"

# memory (in MB):
#   auto -> 1/4 of system RAM
#   1536 -> 1.5 GB RAM
memory: 2048

# cpu:
#   auto -> max number of CPU cores
#      2 -> 2 CPU cores
cpus: 2

# vram (in MB):
#   video memory (currently vbox only)
vram: 100

# Provisioning features
provision:
    # do full system update for each full provisoning
    update: true

    # apt packages
    apt: []

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/Projects/cphalcon
      to: /home/vagrant/workspace/phalcon/cphalcon

# Sites configuration.
#
# You can use the "type" parameter to specify the type
# of Nginx configuration for the site. For example:
#
# - map:  landing.local
#   to:   /home/vagrant/workspace/landing/public
#   type: spa
#
# The default type is "phalcon".
#
# If the desired type is not allowed "phalcon" will be used as fallback.
#
# Available types:
#   - phalcon
#   - slayer
#   - phanbook
#   - proxy
#   - spa
#   - silverstripe
#   - symfony2
#   - statamic
#   - laravel
#   - zend
sites:
    - map: phalcon.local
      to:  /home/vagrant/workspace/phalcon/public

databases:
    - phalcondb

#blackfire:
#    - id: foo
#      token: bar
#      client_id: foo
#      client_token: bar

#ports:
#    - send: 50000
#      to: 5000
#    - send: 7777
#      to: 777
#      protocol: udp

# verbose:
#   Set provision verbosity to obtain detailed logging.
#   Default value is false (minimal verbosity). Examples:
#
#   false -> minimal verbosity
#    true -> equivalent to v
#    -vvv -> equivalent to vvv
#    vvvv -> maximal verbosity
verbose: false

```

### Vagrant up output

https://gist.github.com/Zaszczyk/c640538155080df116e70c275e613c66

### Details

- Vagrant: 1.9.7
- Provider: Virtualbox (5.1.22)
- Phalcon Box: v2.5.0
- Operating System: macOS 10.12.5
- Other related info (if any):
- Ruby: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]

Virtualbox users, please upgrade to `~5.1`. You will show as up-to-date from the `~5.0` branch when you
`About -> Check for Updates`. You'll need to download a newer version of Virtualbox. 
See: https://www.virtualbox.org/wiki/Downloads

### References
None.
