### ISSUE TITLE
Having multiple sites and folders results in: the python pyOpenSSL module is required

### ISSUE THREAD

**Issue by alphadijkstra** [phalcon/box#83]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

## Steps to reproduce

[This issue does not happen if you start fresh without any previously created box. You can delete your previous box with ``vagrant destroy``]

1. Run the vagrant box with the standard settings.
1. Add more sites and folders to ``settings.yml`` (an equal amount in my case)
2. Run ``vagrant up --provision`` or ``vagrant reload --provision``

### Expected behavior

Adding the sites and folders to nginx. 
I'm trying to access 2 sites in 2 folders in my ``www`` directory.

### Actual behavior

Error message in commandprompt/powershell: ``the python pyOpenSSL module is required``

### Host operating system

Windows 10 Pro

### `settings.yml`

```yaml
---
# ------------------------------------------------------------
# Phalcon Box Configurations
# ------------------------------------------------------------
#

# Name of VM
name: pbox

# VM provider
#
# Available providers:
#   - virtualbox
#   - vmware_fusion
#   - vmware_workstation
provider: virtualbox

# Enable GUI mode (show screen of VM)
gui: false

ip: "192.168.50.4"

# memory (in MB):
#   auto -> 1/4 of system RAM
#   1536 -> 1.5 GB RAM
memory: 4096

# cpu:
#   auto -> max number of CPU cores
#      2 -> 2 CPU cores
cpus: 2

# vram (in MB):
#   video memory (currently vbox only)
vram: 100

# Provisioning features
provision:
    # do full system update for each full provisoning
    update: true

    # apt packages
    apt: []

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ../www/web
      to: /home/vagrant/workspace/phalcon/web
    - map: ../www/api
      to: /home/vagrant/workspace/phalcon/api

# Sites configuration.
#
# You can use the "type" parameter to specify the type
# of Nginx configuration for the site. For example:
#
# - map:  landing.local
#   to:   /home/vagrant/workspace/landing/public
#   type: spa
#
# The default type is "phalcon".
#
# If the desired type is not allowed "phalcon" will be used as fallback.
#
# Available types:
#   - phalcon
#   - slayer
#   - phanbook
#   - proxy
#   - spa
#   - silverstripe
#   - symfony2
#   - statamic
#   - laravel
#   - zend
sites:
    - map: web-ontrack.local
      to:  /home/vagrant/workspace/phalcon/web/public
    - map: api-ontrack.local
      to:  /home/vagrant/workspace/phalcon/api/public

databases:
    - phalcondb

#blackfire:
#    - id: foo
#      token: bar
#      client_id: foo
#      client_token: bar

#ports:
#    - send: 50000
#      to: 5000
#    - send: 7777
#      to: 777
#      protocol: udp

# verbose:
#   Set provision verbosity to obtain detailed logging.
#   Default value is false (minimal verbosity). Examples:
#
#   false -> minimal verbosity
#    true -> equivalent to v
#    -vvv -> equivalent to vvv
#    vvvv -> maximal verbosity
verbose: false
```

### Vagrant up output

```
Bringing machine 'pbox' up with 'virtualbox' provider...
==> pbox: Checking if box 'phalconphp/xenial64' is up to date...
==> pbox: Running provisioner: shell...
    pbox: Running: script: Configure the public key for SSH access
==> pbox: Running provisioner: shell...
    pbox: Running: inline script
==> pbox: Running provisioner: shell...
    pbox: Running: script: Clear environment variables
==> pbox: Running provisioner: ansible_local...
    pbox: Running ansible-playbook...

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [pbox]

TASK [Obtain the stats of site OpenSSL configuration] **************************
ok: [pbox] => (item={u'map': u'web-ontrack.local', u'to': u'/home/vagrant/workspace/phalcon/web/public'})
ok: [pbox] => (item={u'map': u'api-ontrack.local', u'to': u'/home/vagrant/workspace/phalcon/api/public'})

TASK [Obtain the stats of site OpenSSL private key] ****************************
ok: [pbox] => (item={u'map': u'web-ontrack.local', u'to': u'/home/vagrant/workspace/phalcon/web/public'})
ok: [pbox] => (item={u'map': u'api-ontrack.local', u'to': u'/home/vagrant/workspace/phalcon/api/public'})

TASK [Obtain the stats of site OpenSSL Certificate] ****************************
ok: [pbox] => (item={u'map': u'web-ontrack.local', u'to': u'/home/vagrant/workspace/phalcon/web/public'})
ok: [pbox] => (item={u'map': u'api-ontrack.local', u'to': u'/home/vagrant/workspace/phalcon/api/public'})

TASK [Create per site OpenSSL configuration] ***********************************
skipping: [pbox] => (item={'_ansible_parsed': True, u'stat': {u'isuid': False, u'uid': 0, u'exists': True, u'attr_flags': u'e', u'woth': False, u'isreg': True, u'device_type': 0, u'mtime': 1502056032.6573687, u'block_size': 4096, u'inode': 3539015, u'isgid': False, u'size': 696, u'executable': False, u'charset': u'us-ascii', u'readable': True, u'version': u'1360180661', u'pw_name': u'root', u'gid': 0, u'ischr': False, u'wusr': True, u'writeable': True, u'mimetype': u'text/x-fortran', u'blocks': 8, u'xoth': False, u'islnk': False, u'nlink': 1, u'issock': False, u'rgrp': True, u'gr_name': u'root', u'path': u'/etc/nginx/ssl/web-ontrack.local.cnf', u'xusr': False, u'atime': 1502056147.617448, u'md5': u'737cdfb4f48cb47b58fd4bc92f0ff27f', u'isdir': False, u'ctime': 1502056032.8694253, u'isblk': False, u'wgrp': False, u'xgrp': False, u'dev': 64512, u'roth': True, u'isfifo': False, u'mode': u'0644', u'checksum': u'44b70865d6227e17eaaee7864c826a3267100730', u'rusr': True, u'attributes': [u'extents']}, '_ansible_item_result': True, '_ansible_no_log': False, u'changed': False, 'item': {u'map': u'web-ontrack.local', u'to': u'/home/vagrant/workspace/phalcon/web/public'}, u'invocation': {u'module_args': {u'checksum_algorithm': u'sha1', u'get_checksum': True, u'follow': False, u'path': u'/etc/nginx/ssl/web-ontrack.local.cnf', u'get_md5': True, u'get_mime': True, u'get_attributes': True}}})
skipping: [pbox] => (item={'_ansible_parsed': True, u'stat': {u'isuid': False, u'uid': 0, u'exists': True, u'attr_flags': u'e', u'woth': False, u'isreg': True, u'device_type': 0, u'mtime': 1502056033.0894847, u'block_size': 4096, u'inode': 3539025, u'isgid': False, u'size': 696, u'executable': False, u'charset': u'us-ascii', u'readable': True, u'version': u'1360180684', u'pw_name': u'root', u'gid': 0, u'ischr': False, u'wusr': True, u'writeable': True, u'mimetype': u'text/x-fortran', u'blocks': 8, u'xoth': False, u'islnk': False, u'nlink': 1, u'issock': False, u'rgrp': True, u'gr_name': u'root', u'path': u'/etc/nginx/ssl/api-ontrack.local.cnf', u'xusr': False, u'atime': 1502056147.7615197, u'md5': u'dd6a6dbebaa9d5d2b0996cf28de3dec6', u'isdir': False, u'ctime': 1502056033.1735077, u'isblk': False, u'wgrp': False, u'xgrp': False, u'dev': 64512, u'roth': True, u'isfifo': False, u'mode': u'0644', u'checksum': u'edb778ac783c84c3a6d5aa328b96c938dc8e7022', u'rusr': True, u'attributes': [u'extents']}, '_ansible_item_result': True, '_ansible_no_log': False, u'changed': False, 'item': {u'map': u'api-ontrack.local', u'to': u'/home/vagrant/workspace/phalcon/api/public'}, u'invocation': {u'module_args': {u'checksum_algorithm': u'sha1', u'get_checksum': True, u'follow': False, u'path': u'/etc/nginx/ssl/api-ontrack.local.cnf', u'get_md5': True, u'get_mime': True, u'get_attributes': True}}})

TASK [Generate per site OpenSSL private key] ***********************************
failed: [pbox] (item={'_ansible_parsed': True, u'stat': {u'exists': False}, '_ansible_item_result': True, '_ansible_no_log': False, u'changed': False, 'item': {u'map': u'web-ontrack.local', u'to': u'/home/vagrant/workspace/phalcon/web/public'}, u'invocation': {u'module_args': {u'checksum_algorithm': u'sha1', u'get_checksum': True, u'follow': False, u'path': u'/etc/nginx/ssl/web-ontrack.local.key', u'get_md5': True, u'get_mime': True, u'get_attributes': True}}}) => {"failed": true, "item": {"changed": false, "invocation": {"module_args": {"checksum_algorithm": "sha1", "follow": false, "get_attributes": true, "get_checksum": true, "get_md5": true, "get_mime": true, "path": "/etc/nginx/ssl/web-ontrack.local.key"}}, "item": {"map": "web-ontrack.local", "to": "/home/vagrant/workspace/phalcon/web/public"}, "stat": {"exists": false}}, "msg": "the python pyOpenSSL module is required"}
failed: [pbox] (item={'_ansible_parsed': True, u'stat': {u'exists': False}, '_ansible_item_result': True, '_ansible_no_log': False, u'changed': False, 'item': {u'map': u'api-ontrack.local', u'to': u'/home/vagrant/workspace/phalcon/api/public'}, u'invocation': {u'module_args': {u'checksum_algorithm': u'sha1', u'get_checksum': True, u'follow': False, u'path': u'/etc/nginx/ssl/api-ontrack.local.key', u'get_md5': True, u'get_mime': True, u'get_attributes': True}}}) => {"failed": true, "item": {"changed": false, "invocation": {"module_args": {"checksum_algorithm": "sha1", "follow": false, "get_attributes": true, "get_checksum": true, "get_md5": true, "get_mime": true, "path": "/etc/nginx/ssl/api-ontrack.local.key"}}, "item": {"map": "api-ontrack.local", "to": "/home/vagrant/workspace/phalcon/api/public"}, "stat": {"exists": false}}, "msg": "the python pyOpenSSL module is required"}
        to retry, use: --limit @/vagrant/provisioning/main.retry

PLAY RECAP *********************************************************************
pbox                       : ok=4    changed=0    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

### Details

- Vagrant: Run `vagrant -v` to show the version
- Provider: 1.9.7
- Phalcon Box: 2.5.0
- Operating System: Windows 10 Pro
- Other related info (if any): None

### References

None

**Comment by poproar** [comment]
Were you able to get this running?

**Comment by zanza54** [comment]
My workaround was to edit the settings file to the amount of sites/folders before running the server for the first time. Doing it afterwards didn't work resulting in the error message.

**Comment by poproar** [comment]
I also discovered vagrant cant mount to directories that do not exist yet on startup

**Comment by AlexVenga** [comment]
Today is the same problem!
I'm trying to add a new site to an existing machine.
MacOS X Sierra 10.12.5 

TASK [Generate per site OpenSSL private key] ***********************************
skipping: [halcon-box-admitad-shoes] => (item={'_ansible_parsed': True, u'stat': {u'isuid': False, u'uid': 0, u'exists': True, u'attr_flags': u'e', u'woth': False, u'isreg': True, u'device_type': 0, u'mtime': 1502226176.975171, u'block_size': 4096, u'inode': 1982048, u'isgid': False, u'size': 3272, u'executable': False, u'charset': u'us-ascii', u'readable': True, u'version': u'18446744072130719997', u'pw_name': u'root', u'gid': 0, u'ischr': False, u'wusr': True, u'writeable': True, u'mimetype': u'text/plain', u'blocks': 8, u'xoth': False, u'islnk': False, u'nlink': 1, u'issock': False, u'rgrp': False, u'gr_name': u'root', u'path': u'/etc/nginx/ssl/phalcon-box-admitad-shoes.dev.key', u'xusr': False, u'atime': 1504820322.8124325, u'md5': u'298912227d4dcc9d88598c8fb3619008', u'isdir': False, u'ctime': 1502226176.975171, u'isblk': False, u'wgrp': False, u'xgrp': False, u'dev': 64512, u'roth': False, u'isfifo': False, u'mode': u'0600', u'checksum': u'c965791e5a34e40d0241eec21e1c27b7e0967974', u'rusr': True, u'attributes': [u'extents']}, '_ansible_item_result': True, '_ansible_no_log': False, u'changed': False, 'item': {u'map': u'phalcon-box-admitad-shoes.dev', u'to': u'/home/vagrant/workspace/phalcon-box-admitad-shoes/dev/public'}, u'invocation': {u'module_args': {u'checksum_algorithm': u'sha1', u'get_checksum': True, u'follow': False, u'path': u'/etc/nginx/ssl/phalcon-box-admitad-shoes.dev.key', u'get_md5': True, u'get_mime': True, u'get_attributes': True}}}) 
failed: [halcon-box-admitad-shoes] (item={'_ansible_parsed': True, u'stat': {u'exists': False}, '_ansible_item_result': True, '_ansible_no_log': False, u'changed': False, 'item': {u'map': u'ourshoe.loc', u'to': u'/home/vagrant/workspace/ourshoe/loc/public'}, u'invocation': {u'module_args': {u'checksum_algorithm': u'sha1', u'get_checksum': True, u'follow': False, u'path': u'/etc/nginx/ssl/ourshoe.loc.key', u'get_md5': True, u'get_mime': True, u'get_attributes': True}}}) => {"failed": true, "item": {"changed": false, "invocation": {"module_args": {"checksum_algorithm": "sha1", "follow": false, "get_attributes": true, "get_checksum": true, "get_md5": true, "get_mime": true, "path": "/etc/nginx/ssl/ourshoe.loc.key"}}, "item": {"map": "ourshoe.loc", "to": "/home/vagrant/workspace/ourshoe/loc/public"}, "stat": {"exists": false}}, "msg": "the python pyOpenSSL module is required"}
	to retry, use: --limit @/vagrant/provisioning/main.retry

**Comment by sergeyklay** [comment]
@poproar Take a look at your configuration:

```yml
folders:
    - map: /Users/ALEX/LocalHost/phalcon-box-admitad-shoes/sites/
      to: /home/vagrant/workspace/

sites:
    - map: phalcon-box-admitad-shoes.dev
      to:  /home/vagrant/workspace/phalcon-box-admitad-shoes/dev/public
    - map: phalcon-box-admitad-shoes.prod
      to:  /home/vagrant/workspace/phalcon-box-admitad-shoes/prod/public
```

Regarding to this configuration the ` /Users/ALEX/LocalHost/phalcon-box-admitad-shoes/sites/` must contain:

* `phalcon-box-admitad-shoes/dev/public`
* `phalcon-box-admitad-shoes/prod/public`

Could you please verify this?
