### ISSUE TITLE
Vagrant up hangs near the end of the process

### ISSUE THREAD

**Issue by maxi032** [phalcon/box#86]
### Actual behavior

  vagrant up hangs

### Host operating system

Windows 10

### `settings.yml`

settings.yml is the default one

### Details
gist file: https://gist.github.com/maxi032/6540916fcc27ef7f41516dcb6d612fa5
vagrant v1.9.7 
virtualbox Version 5.1.26 r117224

**Comment by sergeyklay** [comment]
Could you please try Vagrant 1.9.8

**Comment by JABirchall** [comment]
I'm having a simular problem

Host is Windows 10 using VMWare

Output: https://gist.githubusercontent.com/JABirchall/bfc61e418fef590c4828c74a067ea144/raw/5e4ad2a3a75a113474fcf9d940578311a09cf13d/2017-08-31_23-22-40.txt

Vagrant 1.9.8

**Comment by sergeyklay** [comment]
> the box was trying to register ip: 192.168.50.4

The networks property of the `settings.yml` configures network interfaces for your Phalcon Box environment. You may configure as many interfaces as necessary:
```yaml
networks:
    - type: "private_network"
      ip: "192.168.50.99" # you may change this IP
```
To enable a bridged interface, configure a bridge setting and change the network type to `public_network`:
```yaml
networks:
    - type: "private_network"
      ip: "192.168.50.99" # you may change this IP
      bridge: "en1: Wi-Fi (AirPort)"
```
To enable DHCP, just remove the ip option from this configuration:
```yaml
networks:
    - type: "private_network"
      bridge: "en1: Wi-Fi (AirPort)"
```
